version: "3.9"
services:
  sp:
    build:
      context: .
      dockerfile: Dockerfile
    image: spidregistry.azurecr.io/sp
    container_name: sp
    env_file:
      - .env
    ports:
      - 8099:80
    volumes:
      - sp_azure:/app/sp_conf
    network_mode: bridge

  idp-testenv:
    image: italia/spid-testenv2
    container_name: idp-testenv
    ports:
      - 8088:8088
    restart: always
    volumes:
      - idp_azure:/app/conf
    network_mode: bridge

volumes:
  sp_azure:
    driver: azure_file
    driver_opts:
      share_name: conf
      storage_account_name: scootrspidsp
  idp_azure:
    driver: azure_file
    driver_opts:
      share_name: conf
      storage_account_name: scootrspididp
