version: "3.9"
services:
  sp:
    build:
      context: .
      dockerfile: Dockerfile
    image: spidregistry.azurecr.io/sp
    container_name: sp
    env_file:
      - .env
    ports:
      - 8099:80
    volumes:
      - type: bind
        source: ./sp_conf
        target: /app/sp_conf
    network_mode: bridge

  idp-testenv:
    image: italia/spid-testenv2
    container_name: idp-testenv
    ports:
      - 8088:8088
    restart: always
    volumes:
      - type: bind
        source: ./idp_conf
        target: /app/conf
    network_mode: bridge
