version: "3.9"
services:
  sp:
    container_name: sp
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8099:80
    volumes:
      - type: bind
        source: ./sp_conf
        target: /var/www/sp_conf
    network_mode: bridge

  idp-testenv:
    container_name: idp-testenv
    image: italia/spid-testenv2
    ports:
      - 8088:8088
    restart: always
    volumes:
      - type: bind
        source: ./idp_conf
        target: /var/www/conf
    network_mode: bridge
